name: uniswap-v3
version: 1.0.0
description: Indexes Uniswap V3 pools, swaps, and liquidity events
repository: https://github.com/zilstream/indexer

dataSources:
  # UniswapV3Factory contract
  - kind: ethereum/contract
    name: UniswapV3Factory
    network: zilliqa
    source:
      # Set to your chain's factory address (optional for topic-only filtering)
      address: "0x000A3ED861B2cC98Cc5f1C0Eb4d1B53904c0c93a"
      abi: UniswapV3Factory
      startBlock: 3862851
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.1
      language: wasm/assemblyscript
      entities:
        - Factory
        - Pool
        - Token
      eventHandlers:
        - event: PoolCreated(indexed address,indexed address,indexed uint24,int24,address)
          handler: handlePoolCreated

  # UniswapV3Pool template - will be instantiated for each pool
  - kind: ethereum/contract
    name: UniswapV3Pool
    network: zilliqa
    source:
      abi: UniswapV3Pool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.1
      language: wasm/assemblyscript
      entities:
        - Pool
        - Swap
        - Mint
        - Burn
        - Collect
      eventHandlers:
        - event: Initialize(uint160,int24)
          handler: handleInitialize
        - event: Swap(indexed address,indexed address,int256,int256,uint160,uint128,int24)
          handler: handleSwap
        - event: Mint(indexed address,indexed int24,indexed int24,uint128,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,indexed int24,indexed int24,uint128,uint256,uint256)
          handler: handleBurn
        - event: Collect(indexed address,address,indexed int24,indexed int24,uint128,uint128)
          handler: handleCollect

# Context for module configuration
context:
  # Factory address for your deployment
  factoryAddress: "0x000A3ED861B2cC98Cc5f1C0Eb4d1B53904c0c93a"
  # Wrapped ZIL (WZIL) address used for pricing; set this to your WZIL token
  wethAddress: "0x94e18aE7dd5eE57B55f30c4B63E2760c09EFb192"
  # USD stablecoins on Zilliqa EVM; used for direct USD valuation in V3
  stablecoins:
    - "0x2274005778063684fbB1BfA96a2b725dC37D75f9" # zUSDT
    - "0xD8b73cEd1B16C047048f2c5EA42233DA33168198" # USDC
    - "0xE9df5b4b1134A3aadf693Db999786699B016239e" # kUSD
  # Optional RPC for token metadata enrichment (leave empty to skip on-chain metadata)
  rpcEndpoint: "http://176.9.25.203:4202"
