name: uniswap-v3
version: 1.0.0
description: Indexes Uniswap V3 pools, swaps, and liquidity events
repository: https://github.com/zilstream/indexer

dataSources:
  # UniswapV3Factory contract
  - kind: ethereum/contract
    name: UniswapV3Factory
    network: zilliqa
    source:
      # Set to your chain's factory address (optional for topic-only filtering)
      address: "0x000A3ED861B2cC98Cc5f1C0Eb4d1B53904c0c93a"
      abi: UniswapV3Factory
      startBlock: 3862851
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.1
      language: wasm/assemblyscript
      entities:
        - Factory
        - Pool
        - Token
      eventHandlers:
        - event: PoolCreated(indexed address,indexed address,indexed uint24,int24,address)
          handler: handlePoolCreated

  # UniswapV3Pool template - will be instantiated for each pool
  - kind: ethereum/contract
    name: UniswapV3Pool
    network: zilliqa
    source:
      abi: UniswapV3Pool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.1
      language: wasm/assemblyscript
      entities:
        - Pool
        - Swap
        - Mint
        - Burn
        - Collect
      eventHandlers:
        - event: Initialize(uint160,int24)
          handler: handleInitialize
        - event: Swap(indexed address,indexed address,int256,int256,uint160,uint128,int24)
          handler: handleSwap
        - event: Mint(indexed address,indexed int24,indexed int24,uint128,uint256,uint256)
          handler: handleMint
        - event: Burn(indexed address,indexed int24,indexed int24,uint128,uint256,uint256)
          handler: handleBurn
        - event: Collect(indexed address,address,indexed int24,indexed int24,uint128,uint128)
          handler: handleCollect

# Context for module configuration
context:
  # Default factory address (override for your deployment)
  factoryAddress: "0x0000000000000000000000000000000000000000"
  # Optional RPC for token metadata enrichment
  rpcEndpoint: ""
